### ISSUE TITLE
Problem booting some app services.

### ISSUE THREAD

**Issue by Khubajsn** [zumicts/Audiotica#287]
Upon starting/resuming the application, an error message with the aforementioned test is displayed.

This problem has started to occur a few days ago. As a possible consequence of this issue, I am unable to enter the 'Now Playing' screen upon resuming the application. The bottom toolbar does not show up, even if Audiotica is playing in the background.

I have tried rebooting my device to no avail. I have not yet tried reinstalling the application from Windows Store. Running Windows 10 Mobile TP on 10536.

Is there any more information I could provide?

**Comment by zumicts** [comment]
On *Windows 10 Mobile TP* you should be using the beta app for win10 until public release.

[Link](https://www.microsoft.com/en-us/store/apps/audiotica/9wzdncrdn9jh)

**Comment by Khubajsn** [comment]
Thanks, installing the beta version now.
I thought it might be worth letting you know that this problem disappeared after I hit the 'Factory Reset' button and recreated my collection.
