### ISSUE TITLE
Html decode match titles in all providers

### ISSUE THREAD

**Issue by zumicts** [zumicts/Audiotica#292]

**Comment by ghost** [comment]
Sorry, where can I follow the development of the app?
'Cause Reddit seems not to be updated...

Thank you

Alberto
Il 19/02/2016 01:10:04, Harold Martinez notifications@github.com ha scritto:
Closed #292 [https://github.com/zumicts/Audiotica/issues/292] via c901972 [https://github.com/zumicts/Audiotica/commit/c901972c03283244f3803d78b7efcaaf6c50b758].

**Comment by haroldma-zz** [comment]
@albertozanardo 

[/r/audioticabeta](http://reddit.com/r/audioticabeta)
