### ISSUE TITLE
Instructions to build for WP 8.1

### ISSUE THREAD

**Issue by kumarharsh** [zumicts/Audiotica#295]
Hello,

I am interested in seeing some changes to the app, and I thought maybe I can give a shot to contributing to this wonderful app. The readme seems to be targeted for Windows 10 specifically. Can you explain which tools I'd need to develop for Windows Phone 8.1?

**Comment by zumicts** [comment]
Windows Phone 8.1 development has been discontinued, in favor of Windows 10.  The old project is still available in the [legacy](https://github.com/zumicts/Audiotica/tree/legacy) branch.
