### ISSUE TITLE
Backup crashes after ~30sec

### ISSUE THREAD

**Issue by mightycoco** [zumicts/Audiotica#56]
Version 1501.1.1.0

About 30 songs in my collection.
There is only a generic popup, a crash was prevented without further information.

**Comment by zumicts** [comment]
There is an update in certification that should have fix the crashing and email report issues.

Do report back if it succeeds one the update goes live, so I can close or fix this issue.

[Code fixing this bug](https://github.com/zumicts/Audiotica/commit/90000cf4b2df0ed81acbc1985fd265849549868f)

**Comment by mightycoco** [comment]
Sorry, same behaviour. I'm on WP8.1.1, HTC 8X, ~6GB free storage... 1GB ram.

The crash report now says:

Insufficient memory to continue the execution of the program.

Details:

**Comment by zumicts** [comment]
I'll get on minimizing the memory usage during backup. How many songs do you have in the app?

**Comment by zumicts** [comment]
This Thursday there will be an update that has fixed this issues.
