### ISSUE TITLE
FR: Prevent screen from locking (configurable)

### ISSUE THREAD

**Issue by mightycoco** [zumicts/Audiotica#99]
Would be nice to have an option to disable automatic screen lock when app is in foreground
(maybe even selectable: &lt;never>, &lt;always>, &lt;only in "now playing" page>)

https://msdn.microsoft.com/library/windows/apps/microsoft.phone.shell.phoneapplicationservice.useridledetectionmode(v=vs.105).aspx

**Comment by zumicts** [comment]
I liked the options ideas :+1: 

IdleDetectionMode is not available in Windows Phone 8.1 apps.  So, no running under lock but they do have [this](https://msdn.microsoft.com/en-us/library/windows/apps/br241816.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1) which prevents the screen from locking by timeout.
